apiVersion: apps/v1
kind: Deployment
metadata:
  name: aadfg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aadfg
  template:
    metadata:
      labels:
        app: aadfg
    spec:
      containers:
      - image: okteto.dev/aadfg:latest
        name: aadfg
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "a031e5eb-4c26-423f-9b4c-e8ae5e1e1a37"
        - name: Vless_Path
          value: "/fgt14gjyu"
        - name: Vmess_UUID
          value: "a031e5eb-4c26-423f-9b4c-e8ae5e1e1a37"
        - name: Vmess_Path
          value: "/fdbsas16ehtd"
        - name: Share_Path
          value: "/v2link"
